
server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #是否开启注册中心路由转发 通过serviceid转发到服务，默认false
      routes:
      # 严格按照缩进 要不然报错或者不起作用，参照官方文档!!
#      - id: time_route
#        uri: http://www.baidu.com
#        predicates:
#        - After=2018-04-22T06:06:06+08:00[Asia/Shanghai] # before between
      # 匹配get请求
#      - id: method_route
#        uri: https://www.baidu.com/
#        predicates:
#        - Method=GET
      # path route predicate 通过接受一个路径参数来段路径是否走路由
      - id: path_route
        uri: http://baidu.com
        predicates:
        - Path=/foo/{segment}
#        # path route predicate 支持传入两个参数 一个是参数名 一个是参数值
#      - id: query_route
#        uri: http://baidu.com
#        predicates:
#        - Query=name,mxf
#        # 添加过滤器
      - id: add_request_parameter_route
        uri: lb://SERVICE-PROVIDER
        filters:
        - AddRequestParameter=name, mxf
        predicates:
        - Path=/hello


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug